name: mlops-example-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Train my model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
        
          # Your ML workflow goes here
          pip install -r requirements.txt
          python model.py
